name: Validation of EvoMaster Action

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trying EvoMaster Action
        uses: ./  # Refers to this custom action
        with:
           args: "--help"
           failOnErrors: true