name: Update Base Tag on Release

on:
  release:
    types:
      - published

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Base Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the release tag name
          TAG_NAME=${{ github.event.release.tag_name }}

          echo "Updating base tag to point to release tag: $TAG_NAME"

          # Fetch all branches and tags
          git fetch --all

          # Create or move the base tag to point to the release tag
          git checkout -B v1 $TAG_NAME

          # Push the updated base tag
          git push origin v1 --force